# Generated by Django 4.0.5 on 2022-12-27 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='', max_length=100)),
                ('lastname', models.CharField(default='', max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(default='', max_length=6)),
                ('emailid', models.CharField(default='', max_length=100)),
                ('mobileno', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=1000)),
                ('state', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
                ('designation', models.CharField(default='', max_length=100)),
                ('managerid', models.IntegerField()),
                ('photograph', models.ImageField(upload_to='static/')),
            ],
        ),
    ]
