# Generated by Django 4.0.5 on 2023-01-02 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeadGenerationApp', '0004_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='manager',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
    ]
