# Generated by Django 4.0.5 on 2023-01-02 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeadGenerationApp', '0005_employee_password_manager_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='', max_length=45)),
                ('lastname', models.CharField(default='', max_length=45)),
                ('dob', models.DateField()),
                ('gender', models.CharField(default='', max_length=6)),
                ('emailid', models.CharField(default='', max_length=45)),
                ('mobileno1', models.CharField(default='', max_length=12)),
                ('organization', models.CharField(default='', max_length=500)),
                ('mobileno2', models.CharField(default='', max_length=12)),
                ('address', models.CharField(default='', max_length=500)),
                ('state', models.CharField(default='', max_length=45)),
                ('city', models.CharField(default='', max_length=45)),
                ('photograph', models.ImageField(upload_to='static/')),
            ],
        ),
    ]
