# Generated by Django 4.0.5 on 2023-01-11 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeadGenerationApp', '0006_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobileno', models.CharField(default='', max_length=1000)),
                ('emailid', models.CharField(default='', max_length=1000)),
                ('adminname', models.CharField(default='', max_length=450)),
                ('password', models.CharField(default='', max_length=45)),
            ],
        ),
    ]
