# Generated by Django 4.0.5 on 2023-01-14 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeadGenerationApp', '0008_calldetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator',
            name='Profilepic',
            field=models.ImageField(default=2, upload_to='static/'),
            preserve_default=False,
        ),
    ]
